import Footer from "../components/Footer";
import Nav from "../components/Nav";
import Head from "next/head";
import "../styles/globals.css";
function MyApp({ Component, pageProps }) {
  return (
    <>
      {/* {changings.map((changing) => (
        <Nav
          key={changing.id}
          logo={changing.logo}
          thumbnail={changing.thumbnail}
        />
      ))} */}
      <Head>
        <title>Tranquility</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/imgs/brand/icon_white.ico" />
      </Head>
      <Nav />
      <Component {...pageProps} />
      <Footer />
    </>
  );
}

export default MyApp;
