import Head from "next/head";
import styles from "../styles/Home.module.css";
import Collection from "../components/Collection";
import { GraphQLClient, gql } from "graphql-request";

const graphcms = new GraphQLClient(
  "https://api-ap-northeast-1.hygraph.com/v2/clb1xr6fr13fv01unfu2j5zhu/master"
);

const QUERY = gql`
  {
    collections {
      title
      image {
        url
      }
    }
  }
`;
export async function getStaticProps() {
  const { collections } = await graphcms.request(QUERY);
  return {
    props: {
      collections,
    },
    revalidate: 10, //10 seconds
  };
}

export default function Home({ collections }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tranquility</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/imgs/brand/icon_white.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.collection__container}>
          {collections.map((collection) => (
            <Collection title={collection.title} image={collection.image} />
          ))}
        </div>
      </main>
    </div>
  );
}
